export const classToCssProperty = {
    "colour-": "color",
    "font-": "fontSize",
    "fontw-": "fontWeight",
    "m-": "margin",
    "p-": "padding",
    "border-": "border",
    "bgcolor-": "backgroundColor",
    "d-": "display",
    "pos-": "position",
    "w-": "width",
    "h-": "height",
    "ta-": "textAlign",
    "flex-": "flex",
    "flexd-": "flexDirection",
    "overflow-": "overflow",
    "opacity-": "opacity",
    "z-": "zIndex",
    "visibility-": "visibility",
    "shadow-": "boxShadow",
    "transition-": "transition",
    "cursor-": "cursor",
    "ac-": "alignContent",
    "jc-": "justifyContent",
    "ai-": "alignItems",
    "br-": "borderRadius",
    "td-": "textDecoration",
    "lst-": "listStyleType",
    "ls-": "letterSpacing",
  };
  